---
- name: Create config for floating ip
  template:
    src: "ifcfg-eth0:1"
    dest: "/etc/sysconfig/network-scripts/ifcfg-eth0:1"

- name: Restart network
  service:
    name: network
    state: restarted
